### ISSUE TITLE
When used StaggeredTile.fit , the log will report an error, but the display will still be normal

### ISSUE THREAD

**Issue by EchoPuda** [letsar/flutter_staggered_grid_view#163]
```
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#66769 NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2647 pos 12: '!_needsLayout'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2647:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
#4      Iterable.forEach (dart:core/iterable.dart:283:30)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:294:29)
#6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
```

<details>
    <summary>flutter doctor -v</summary>

```
  [✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/zhengjiaming/Flutter1.20.2/flutter
    • Framework revision 1aafb3a8b9 (4 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zhengjiaming/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/zhengjiaming/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • MI CC 9 (mobile) • fd28aa76 • android-arm64 • Android 10 (API 29)
```

</details>

When used `StaggeredTile.fit` , the log will report an error, but the display will still be normal.
You can reproduce it in the Example08, "random dynamic title sizes"

**Comment by icecandy** [comment]
I have this too using SliverStaggeredGrid.countBuilder. Seems to render OK though.

**Comment by EchoPuda** [comment]
@icecandy 
Whether it's countBuilder or count, it is normal not to use `StaggeredTile.fit`.
However, using `StaggeredTile.fit` during debugging will issue an error.
```
    staggeredTileBuilder: (index) {
        return StaggeredTile.fit(2);
    },
```

I also found that:

```
  /// Returns the semantics that this node would like to add to its parent.
  _SemanticsFragment _getSemanticsForParent({
    required bool mergeIntoParent,
  }) {
    assert(mergeIntoParent != null);
    assert(!_needsLayout, 'Updated layout information required for $this to calculate semantics.');
   
    ...

```

This may be due to this `_needsLayout`.
You can reproduce it in the Example08, debug.

**Comment by aboutlan** [comment]
I have the same problem

**Comment by xyhxx** [comment]
Me too, there seems to be no problem. I need to care about it?

**Comment by ZeckoVicath** [comment]
I have the same issue in a gallery view, error thrown, renders normal though

```
'package:flutter/src/rendering/object.dart': Failed assertion: line 2658 pos 12: '!_needsLayout': Updated layout information required for RenderIndexedSemantics#48a51 NEEDS-LAYOUT to calculate semantics.
Stack trace: ```#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2658:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2680:61)
#4      Iterable.forEach (dart:core/iterable.dart:257:30)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
```

I appreciate fixing this error, as it fills the logs needlesly.

**Comment by EchoPuda** [comment]
I changed the waterfall stream widget, and I will close this comment.

**Comment by EchoPuda** [comment]
@aboutlan you can fix it locally and use, or change a waterfall-stream widget.

**Comment by EchoPuda** [comment]
@aboutlan you can fix it locally and use, or change a waterfall-stream widget.

**Comment by yasinarik** [comment]
> I changed the waterfall stream widget, and I will close this comment.

What is the `waterfall stream widget`, how did you solve this error? Thanks a lot

**Comment by EchoPuda** [comment]
@yasinarik change a Widget, don't use this.
you can try this one. https://pub.flutter-io.cn/packages/waterfall_flow
