### ISSUE TITLE
[assert] SliverStaggeredGrid.extentBuilder / StaggeredTile.fit(1)

### ISSUE THREAD

**Issue by dipi0123** [letsar/flutter_staggered_grid_view#166]
SliverStaggeredGrid.extentBuilder / StaggeredTile.fit(1)

An error occurs when the app scrolls all the way up. Is there a workaround?

```
class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: [
        SliverStaggeredGrid.extentBuilder(
          maxCrossAxisExtent: 800,
          mainAxisSpacing: 6.0,
          itemCount: 2,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              width: 800,
              height: 1000,
              color: Colors.grey,
              alignment: Alignment.center,
              child: Text("Button\nNO. $index"),
            );
          },
          staggeredTileBuilder: (int index) => StaggeredTile.fit(1),
        ),
      ],
    );
  }
}
```

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#025ee NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2658 pos 12: '!_needsLayout'

**Comment by mustafaMtfa** [comment]
+1

**Comment by wangBlue** [comment]
I had the same problem

**Comment by mlopez0** [comment]
Same problem here!

`
  static _doThrowNew(int assertionStart, int assertionEnd, Object? message)
      native "AssertionError_throwNew";
  static _doThrowNewSource(String failedAssertion, int line, int column,
      Object? message) native "AssertionError_throwNewSource";
`

Does anyone have a workaround?

**Comment by hasToDev** [comment]
In debug mode, code below :
```
FutureBuilder<List>(
   future: _initialData(),
   builder: (context, snapshot) {            
       return StaggeredGridView.countBuilder(                 
             crossAxisCount: 4,
             mainAxisSpacing: 6,
             crossAxisSpacing: 6,
             itemCount: snapshot.data!.length,                  
             itemBuilder: (BuildContext context, int index) {
               return GridTile(asset: snapshot.data![index]);
             },
             staggeredTileBuilder: (int index) => StaggeredTile.fit(2),
       );
   }
)
```
throws this error :
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#03f92 NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2658 pos 12: '!_needsLayout'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2658:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2680:61)
#4      Iterable.forEach (dart:core/iterable.dart:257:30)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
#6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2765:5)
...
====================================================================================================
```

although, in release mode everything works fine. no error thrown.

**Comment by Tom3652** [comment]
Same issue with the ```SliverStaggeredGrid.countBuilder```. 

I have also asked a question on [StackOverFlow](https://stackoverflow.com/questions/67346685/flutter-renderobject-assertion-failure?noredirect=1#comment119039380_67346685) about it but still no answer.

**Comment by yasinarik** [comment]
```
#4      Iterable.forEach  (dart:core/iterable.dart:257:30)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren 
package:flutter_staggered_grid_view/…/rendering/sliver_variable_size_box_adaptor.dart:296
#6      RenderObject.visitChildrenForSemantics 
package:flutter/…/rendering/object.dart:2765
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Updated layout information required for RenderIndexedSemantics#75e30 NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2658 pos 12: '!_needsLayout'
════════════════════════════════════════════════════════════════════════════════
```

This happens to me also.

**Comment by EdsonBueno** [comment]
Same here.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
