### ISSUE TITLE
The method 'visitChildren' was called on null

### ISSUE THREAD

**Issue by Cretezy** [letsar/flutter_staggered_grid_view#19]
Sometimes, the plugin calls `visitChildren` on null, meaning the widget either wasn't even created yet, or was disposed.

https://github.com/letsar/flutter_staggered_grid_view/blob/1f532380b867b677b646c6608ca98d69aaff64eb/lib/src/widgets/automatic_keep_alive_variable_size_box.dart#L128

```
I/flutter ( 8887): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8887): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter ( 8887): The method 'visitChildren' was called on null.
I/flutter ( 8887): Receiver: null
I/flutter ( 8887): Tried calling: visitChildren(Closure: (Element) => Null)
I/flutter ( 8887): 
I/flutter ( 8887): When the exception was thrown, this was the stack:
I/flutter ( 8887): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 8887): #1      _AutomaticKeepAliveState._getChildElement (package:flutter_staggered_grid_view/src/widgets/automatic_keep_alive_variable_size_box.dart:128:13)
I/flutter ( 8887): #2      _AutomaticKeepAliveState._addClient.<anonymous closure> (package:flutter_staggered_grid_view/src/widgets/automatic_keep_alive_variable_size_box.dart:93:30)
I/flutter ( 8887): #3      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8887): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
I/flutter ( 8887): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 8887): #6      _invoke (dart:ui/hooks.dart:145:13)
I/flutter ( 8887): #7      _drawFrame (dart:ui/hooks.dart:134:3)
I/flutter ( 8887): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Cretezy** [comment]
I'll try to find one. This was a while back and I had worked around this issue

**Comment by jamesblasco** [comment]
Let's open this issue if the problem happens again
