### ISSUE TITLE
'estimatedMaxScrollOffset >= endScrollOffset - leadingScrollOffset': is not true.

### ISSUE THREAD

**Issue by zhoujinliang** [letsar/flutter_staggered_grid_view#313]
The following assertion was thrown during performLayout():
'package:flutter_staggered_grid_view/src/rendering/sliver_masonry_grid.dart': Failed assertion: line
624 pos 9: 'estimatedMaxScrollOffset >= endScrollOffset - leadingScrollOffset': is not true.

The relevant error-causing widget was:
  MasonryGridView
  MasonryGridView:file:///Users/..../discover_screen.dart:72:34

When the exception was thrown, this was the stack:
#2      RenderSliverMasonryGrid.performLayout (package:flutter_staggered_grid_view/src/rendering/sliver_masonry_grid.dart:624:9)
sliver_masonry_grid.dart:624
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
object.dart:2395
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
sliver_padding.dart:139
#5      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361:11)
sliver_padding.dart:361
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
object.dart:2395
#7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
viewport.dart:534
#8      RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1882:12)
viewport.dart:1882
#9      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1833:20)
viewport.dart:1833
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
object.dart:2395
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
box.dart:2386
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
proxy_box.dart:122
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
object.dart:2395
#14     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)

**Comment by letsar** [comment]
Can you give me a way to reproduce it? Which flutter version do you use?

**Comment by gpf0205** [comment]
I have also encountered this issue. When using MasonryGridView.builder in SmartRefresher, after performing a pull-down refresh and scrolling the list multiple times, the issue should be reproducible.

**Comment by gpf0205** [comment]
@letsar

**Comment by angeldragon** [comment]
me too, please resolve it, we are wait for your

**Comment by Moyout** [comment]
me too

**Comment by siulun234** [comment]
I got this error too

**Comment by NicofnCHINA** [comment]
1加手机  
`CustomScrollView(
        physics: widget.canRefresh ? null : const ClampingScrollPhysics(),
        slivers: [
          SliverMasonryGrid.count(    //  154
            crossAxisCount: 2,
            mainAxisSpacing: 8,
            crossAxisSpacing: 8,
            childCount: channelItems[index].effectItems?.length ?? 0,
            itemBuilder: (context, itemIndex) {
              final item = channelItems[index].effectItems![itemIndex];
              return widget.itemBuilder!(context, channelItems[index], item);
            },
          ),
        ],
      ),`

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter_staggered_grid_view/src/rendering/sliver_masonry_grid.dart': Failed assertion: line 624 pos 9: 'estimatedMaxScrollOffset >= endScrollOffset - leadingScrollOffset': is not true.

The relevant error-causing widget was: 
  SliverMasonryGrid SliverMasonryGrid:file:///Users/niudengjun/aisphere-app/apps/app_pixverse/lib/pages/home/template2/effect_gridview.dart:154:29
When the exception was thrown, this was the stack: 
#2      RenderSliverMasonryGrid.performLayout (package:flutter_staggered_grid_view/src/rendering/sliver_masonry_grid.dart:624:9)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#4      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
#5      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1516:12)
#6      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1427:20)
#7      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#8      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#9      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)

**Comment by himankBellpost** [comment]
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter_staggered_grid_view/src/rendering/sliver_masonry_grid.dart': Failed assertion: line 624 pos 9: 'estimatedMaxScrollOffset >= endScrollOffset - leadingScrollOffset': is not true.

Still getting this issue
