### ISSUE TITLE
Not working inside scrollview, row or column

### ISSUE THREAD

**Issue by akashmi** [letsar/flutter_staggered_grid_view#39]
I want to show content below the staggered_grid_view. 
if I put staggered_grid_view inside the scroll view, row or column then it is not working.
```
 I/flutter ( 9770): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 9770): The following assertion was thrown during performResize():
I/flutter ( 9770): Vertical viewport was given unbounded height.
I/flutter ( 9770): Viewports expand in the scrolling direction to fill their container.In this case, a vertical
I/flutter ( 9770): viewport was given an unlimited amount of vertical space in which to expand. This situation
I/flutter ( 9770): typically happens when a scrollable widget is nested inside another scrollable widget.
I/flutter ( 9770): If this widget is always nested in a scrollable widget there is no need to use a viewport because
I/flutter ( 9770): there will always be enough vertical space for the children. In this case, consider using a Column
I/flutter ( 9770): instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
I/flutter ( 9770): the height of the viewport to the sum of the heights of its children.
I/flutter ( 9770): 
I/flutter ( 9770): When the exception was thrown, this was the stack:
I/flutter ( 9770): #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1129:15)
I/flutter ( 9770): #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1182:6)
I/flutter ( 9770): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:9)
I/flutter ( 9770): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #19     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 9770): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #24     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter ( 9770): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #26     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 9770): #27     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter ( 9770): #28     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 9770): #29     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 9770): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #34     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter ( 9770): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #51     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
I/flutter ( 9770): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #53     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 9770): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #55     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 9770): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 9770): #67     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter ( 9770): #68     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 9770): #69     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 9770): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 9770): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 9770): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 9770): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9770): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9770): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 9770): #77     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 9770): #78     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 9770): #79     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 9770): (elided one frame from package dart:async)
I/flutter ( 9770): 

```

**Comment by akashmi** [comment]
I have added  shrinkWrap: true, then it is showing but still getting scrolling issues.

**Comment by jwmuchow** [comment]
I am attempting to add StaggeredGridView.count into a Column. I get the following error.

Any suggestions?

~~~~~~

flutter: viewport was given an unlimited amount of vertical space in which to expand. This situation
flutter: typically happens when a scrollable widget is nested inside another scrollable widget.
flutter: If this widget is always nested in a scrollable widget there is no need to use a viewport because
flutter: there will always be enough vertical space for the children. In this case, consider using a Column
flutter: instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
flutter: the height of the viewport to the sum of the heights of its children.

**Comment by BlueskyFR** [comment]
PLEASE comment your first post here, it seems like you referenced many issues in a single post.

**Comment by Nolence** [comment]
Add `primary: false` to the grid constructor

**Comment by Wizok** [comment]
> Adding `primary: false` to the grid constructor got rid of the scrolling issues for me

Thanks a lot ! this solve my scroll problems, Love you =D
