### ISSUE TITLE
Sometimes exceptions are thrown

### ISSUE THREAD

**Issue by csshuai** [letsar/flutter_staggered_grid_view#50]
```
dependencies:
    flutter_staggered_grid_view: ^0.2.7
```

```
22:58:53.521 255 info flutter.tools  ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
22:58:53.534 256 info flutter.tools  The following NoSuchMethodError was thrown during performLayout():
22:58:53.534 257 info flutter.tools  The getter 'parentData' was called on null.
22:58:53.534 258 info flutter.tools  Receiver: null
22:58:53.534 259 info flutter.tools  Tried calling: parentData
22:58:53.534 260 info flutter.tools 
22:58:53.534 261 info flutter.tools  When the exception was thrown, this was the stack:
22:58:53.551 262 info flutter.tools  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
22:58:53.551 263 info flutter.tools  #1      RenderSliverVariableSizeBoxAdaptor.remove (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:209:15)
22:58:53.551 264 info flutter.tools  #2      SliverVariableSizeBoxAdaptorElement.removeChildRenderObject (package:flutter_staggered_grid_view/src/widgets/sliver.dart:313:18)
22:58:53.551 265 info flutter.tools  #3      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:4744:36)
22:58:53.551 266 info flutter.tools  #4      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2867:13)
22:58:53.551 267 info flutter.tools  #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
22:58:53.551 268 info flutter.tools  #6      Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2866:5)
22:58:53.551 269 info flutter.tools  #7      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2867:13)
22:58:53.551 270 info flutter.tools  #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
22:58:53.551 271 info flutter.tools  #9      Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2866:5)
22:58:53.551 272 info flutter.tools  #10     Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2867:13)
22:58:53.552 273 info flutter.tools  #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
22:58:53.554 274 info flutter.tools  #12     Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2866:5)
22:58:53.554 275 info flutter.tools  #13     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2996:11)
22:58:53.554 276 info flutter.tools  #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2741:9)
22:58:53.554 277 info flutter.tools  #15     SliverVariableSizeBoxAdaptorElement.updateChild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:170:36)
22:58:53.554 278 info flutter.tools  #16     SliverVariableSizeBoxAdaptorElement.removeChild.<anonymous closure> (package:flutter_staggered_grid_view/src/widgets/sliver.dart:201:32)
22:58:53.554 279 info flutter.tools  #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
22:58:53.555 280 info flutter.tools  #18     SliverVariableSizeBoxAdaptorElement.removeChild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:197:11)
22:58:53.555 281 info flutter.tools  #19     List.forEach (dart:core-patch/growable_array.dart:278:8)
22:58:53.555 282 info flutter.tools  #20     RenderSliverVariableSizeBoxAdaptor.collectGarbage.<anonymous closure> (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:342:12)
22:58:53.555 283 info flutter.tools  #21     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
22:58:53.557 284 info flutter.tools  #22     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
22:58:53.557 285 info flutter.tools  #23     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
22:58:53.557 286 info flutter.tools  #24     RenderSliverVariableSizeBoxAdaptor.collectGarbage (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:328:5)
22:58:53.557 287 info flutter.tools  #25     RenderSliverStaggeredGrid.performLayout (package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart:364:5)
22:58:53.557 288 info flutter.tools  #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
22:58:53.558 289 info flutter.tools  #27     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
22:58:53.558 290 info flutter.tools  #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
22:58:53.559 291 info flutter.tools  #29     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
22:58:53.559 292 info flutter.tools  #30     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
22:58:53.559 293 info flutter.tools  #31     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
22:58:53.561 294 info flutter.tools  #32     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
22:58:53.561 295 info flutter.tools  #33     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
22:58:53.561 296 info flutter.tools  #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
22:58:53.561 297 info flutter.tools  #35     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
22:58:53.561 298 info flutter.tools  #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
22:58:53.561 299 info flutter.tools  #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
22:58:53.562 300 info flutter.tools  #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
22:58:53.563 301 info flutter.tools  #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
22:58:53.563 302 info flutter.tools  #43     _invoke (dart:ui/hooks.dart:219:10)
22:58:53.563 303 info flutter.tools  #44     _drawFrame (dart:ui/hooks.dart:178:3)
22:58:53.563 304 info flutter.tools  (elided 3 frames from package dart:async)
22:58:53.580 305 info flutter.tools 
22:58:53.580 306 info flutter.tools  The following RenderObject was being processed when the exception was fired:
22:58:53.580 307 info flutter.tools    RenderSliverStaggeredGrid#6bd71 relayoutBoundary=up2 NEEDS-LAYOUT
22:58:53.580 308 info flutter.tools    creator: SliverStaggeredGrid ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#4d84d] ←
22:58:53.580 309 info flutter.tools    Semantics ← Listener ← _GestureSemantics ←
22:58:53.580 310 info flutter.tools    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#2bfc9] ← Listener ← _ScrollableScope
22:58:53.580 311 info flutter.tools    ← _ScrollSemantics-[GlobalKey#e7695] ← Scrollable ← ⋯
22:58:53.580 312 info flutter.tools    parentData: paintOffset=Offset(12.0, 0.0) (can use size)
22:58:53.580 313 info flutter.tools    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward,
22:58:53.580 314 info flutter.tools    ScrollDirection.reverse, scrollOffset: 9886.5, remainingPaintExtent: 796.0, crossAxisExtent:
22:58:53.580 315 info flutter.tools    390.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 796.0,
22:58:53.580 316 info flutter.tools    remainingCacheExtent: 1296.0 cacheOrigin: -238.0 )
22:58:53.580 317 info flutter.tools    geometry: SliverGeometry(scrollExtent: 11130.9, paintExtent: 796.0, maxPaintExtent: 11130.9,
22:58:53.580 318 info flutter.tools    hasVisualOverflow: true, cacheExtent: 1296.0)
22:58:53.580 319 info flutter.tools    currently live children:
22:58:53.580 320 info flutter.tools    153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176
22:58:53.581 321 info flutter.tools  This RenderObject had the following descendants (showing up to depth 5):
22:58:53.581 322 info flutter.tools    RenderIndexedSemantics#8f221
22:58:53.582 323 info flutter.tools      RenderRepaintBoundary#dba82
22:58:53.582 324 info flutter.tools        RenderClipRRect#8dd69
22:58:53.582 325 info flutter.tools          RenderStack#db0c3
22:58:53.582 326 info flutter.tools            RenderDecoratedBox#45a0e
22:58:53.582 327 info flutter.tools            RenderDecoratedBox#59a86 relayoutBoundary=up1
22:58:53.583 328 info flutter.tools            RenderSemanticsAnnotations#54eb2
22:58:53.583 329 info flutter.tools    RenderIndexedSemantics#ddbaa
22:58:53.583 330 info flutter.tools      RenderRepaintBoundary#d2a8a
22:58:53.583 331 info flutter.tools        RenderClipRRect#6a277
22:58:53.583 332 info flutter.tools          RenderStack#3e2d5
22:58:53.584 333 info flutter.tools            RenderDecoratedBox#b1c0e
22:58:53.584 334 info flutter.tools            RenderDecoratedBox#6825b relayoutBoundary=up1
22:58:53.584 335 info flutter.tools            RenderSemanticsAnnotations#7cd39
22:58:53.584 336 info flutter.tools    RenderIndexedSemantics#d90ce
22:58:53.584 337 info flutter.tools      RenderRepaintBoundary#98a90
22:58:53.584 338 info flutter.tools        RenderClipRRect#ec89c
22:58:53.584 339 info flutter.tools          RenderStack#79af4
22:58:53.586 340 info flutter.tools            RenderDecoratedBox#5591b
22:58:53.586 341 info flutter.tools            RenderDecoratedBox#8e709 relayoutBoundary=up1
22:58:53.586 342 info flutter.tools            RenderSemanticsAnnotations#a03ff
22:58:53.586 343 info flutter.tools    RenderIndexedSemantics#c4622
22:58:53.586 344 info flutter.tools      RenderRepaintBoundary#4f8a3
22:58:53.586 345 info flutter.tools        RenderClipRRect#46b38
22:58:53.587 346 info flutter.tools          RenderStack#bbd29
22:58:53.587 347 info flutter.tools            RenderDecoratedBox#95608
22:58:53.587 348 info flutter.tools            RenderDecoratedBox#4d9eb relayoutBoundary=up1
22:58:53.587 349 info flutter.tools            RenderSemanticsAnnotations#78f70
22:58:53.587 350 info flutter.tools  ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zolzaya** [comment]
Any news?

**Comment by OPY-bbt** [comment]
same problem

**Comment by mickykebe** [comment]
Same problem.

**Comment by mickykebe** [comment]
Tried adding
`if(child == null) {
  return;
}`
before parentData was accessed on the offending line. Another error is thrown in that case.
```
A RenderObject was still attached when attempting to deactivate its RenderObjectElement:
I/flutter ( 6385): RenderIndexedSemantics#06c33
I/flutter ( 6385): 'package:flutter/src/widgets/framework.dart':
I/flutter ( 6385): Failed assertion: line 4920 pos 12: '!renderObject.attached'
I/flutter ( 6385):
I/flutter ( 6385): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6385): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6385): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6385):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6385):
I/flutter ( 6385): When the exception was thrown, this was the stack:
I/flutter ( 6385): #2      RenderObjectElement.deactivate (package:flutter/src/widgets/framework.dart:4920:12)
I/flutter ( 6385): #3      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1755:13)        
I/flutter ( 6385): #4      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
I/flutter ( 6385): #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1757:13)        
I/flutter ( 6385): #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
I/flutter ( 6385): #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1757:13)        
I/flutter ( 6385): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
I/flutter ( 6385): #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1757:13)        
I/flutter ( 6385): #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
I/flutter ( 6385): #11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1757:13)        
I/flutter ( 6385): #12     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1766:7)
I/flutter ( 6385): #13     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3120:29)
I/flutter ( 6385): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2864:9)
I/flutter ( 6385): #15     SliverVariableSizeBoxAdaptorElement.updateChild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:170:36)
I/flutter ( 6385): #16     SliverVariableSizeBoxAdaptorElement.removeChild.<anonymous closure> (package:flutter_staggered_grid_view/src/widgets/sliver.dart:201:32)
I/flutter ( 6385): #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 6385): #18     SliverVariableSizeBoxAdaptorElement.removeChild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:197:11)
I/flutter ( 6385): #19     List.forEach (dart:core-patch/growable_array.dart:278:8)
I/flutter ( 6385): #20     RenderSliverVariableSizeBoxAdaptor.collectGarbage.<anonymous closure> (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:345:12)
I/flutter ( 6385): #21     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
I/flutter ( 6385): #22     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter ( 6385): #23     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
I/flutter ( 6385): #24     RenderSliverVariableSizeBoxAdaptor.collectGarbage (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:331:5)
I/flutter ( 6385): #25     RenderSliverStaggeredGrid.performLayout (package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart:364:5)
I/flutter ( 6385): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6385): #27     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter ( 6385): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6385): #29     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 6385): #30     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter ( 6385): #31     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter ( 6385): #32     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 6385): #33     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 6385): #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 6385): #35     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 6385): #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 6385): #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 6385): #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 6385): #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 6385): #43     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 6385): #44     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 6385): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 6385): 
I/flutter ( 6385): The following RenderObject was being processed when the exception was fired: RenderSliverStaggeredGrid#a47e8 
relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter ( 6385):   needs compositing
I/flutter ( 6385):   creator: SliverStaggeredGrid ← StreamBuilder<int> ← NewsGrid ← SliverPadding ← Viewport ←
I/flutter ( 6385):     IgnorePointer-[GlobalKey#d25fb] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 6385):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#04ed4] ← Listener ← _ScrollableScope       
I/flutter ( 6385):     ← ⋯
I/flutter ( 6385):   parentData: paintOffset=Offset(8.0, 0.0) (can use size)
I/flutter ( 6385):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward,
I/flutter ( 6385):     scrollOffset: 929.3, remainingPaintExtent: 627.4, crossAxisExtent: 395.4, crossAxisDirection:
I/flutter ( 6385):     AxisDirection.right, viewportMainAxisExtent: 627.4, remainingCacheExtent: 1127.4 cacheOrigin:
I/flutter ( 6385):     -242.0 )
I/flutter ( 6385):   geometry: SliverGeometry(scrollExtent: 8301.8, paintExtent: 627.4, maxPaintExtent: 8301.8,
I/flutter ( 6385):     hasVisualOverflow: true, cacheExtent: 1127.4)
I/flutter ( 6385):   currently live children: 4,5,6,7,8,9,10,11
I/flutter ( 6385): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 6385):     child with index 4: RenderIndexedSemantics#5c030
I/flutter ( 6385):       child: RenderRepaintBoundary#cae53 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):         child: RenderSemanticsAnnotations#f5fb9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE       
I/flutter ( 6385):           child: RenderPadding#6bacb NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):             child: RenderPhysicalShape#45314 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):     child with index 5: RenderIndexedSemantics#6788f
I/flutter ( 6385):       child: RenderRepaintBoundary#64389 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):         child: RenderSemanticsAnnotations#798c6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE       
I/flutter ( 6385):           child: RenderPadding#cf1ed NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):             child: RenderPhysicalShape#f19f7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):     child with index 6: RenderIndexedSemantics#cbbc0
I/flutter ( 6385):       child: RenderRepaintBoundary#7110e NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):         child: RenderSemanticsAnnotations#fd263 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE       
I/flutter ( 6385):           child: RenderPadding#8db04 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):             child: RenderPhysicalShape#a0b5a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):     child with index 7: RenderIndexedSemantics#215e0
I/flutter ( 6385):       child: RenderRepaintBoundary#59afa
I/flutter ( 6385):         child: RenderSemanticsAnnotations#ac8bb NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):           child: RenderPadding#8208c NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):             child: RenderPhysicalShape#ccba5 NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):     child with index 8: RenderIndexedSemantics#8eb56
I/flutter ( 6385):       child: RenderRepaintBoundary#85323 NEEDS-PAINT
I/flutter ( 6385):         child: RenderSemanticsAnnotations#ef5eb NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):           child: RenderPadding#ee668 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):             child: RenderPhysicalShape#8046d NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6385):     ...(descendants list truncated after 25 lines)
```

**Comment by mickykebe** [comment]
Has anyone found any fixes/workarounds for this.

**Comment by mpigorini** [comment]
Same problem, any update?

**Comment by OliverKong** [comment]
Set addAutomaticKeepAlives: false
Can solve the problem.

**Comment by pei625569** [comment]
how to deal?

**Comment by pei625569** [comment]
> Set addAutomaticKeepAlives: false
> Can solve the problem.

but i want to set this property,how do?

**Comment by ThinkSimple** [comment]
Im also getting this error, but I think @OliverKong answer helped fixing this problem.

**Comment by goashwin** [comment]
An alternative is to slow down scroll speed. For us, that's untenable because the lists can have thousands of items and it takes 90 seconds to reach the bottom.

The @OliverKong solution works for our use case.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
