### ISSUE TITLE
GridView throws error

### ISSUE THREAD

**Issue by FilipeOS** [letsar/flutter_staggered_grid_view#53]
Hi guys,

So I wanted a "masonry" style on my GridView and I found this awesome plugin, I tried to update the code but it's giving issues and I need some advise please:

My app code:
```
return StaggeredGridView.countBuilder(
                        padding: EdgeInsets.all(10.0),
                        scrollDirection: Axis.vertical,
                        shrinkWrap: true,
                        staggeredTileBuilder: (int index) => new StaggeredTile.fit(2),
                        mainAxisSpacing: 10.0,
                        crossAxisSpacing: 10.0,
                        itemBuilder: (context, index) {
                          return buildItem(context, snapshot.data.documents[index]);
                        },
                        itemCount: snapshot.data.documents.length,
                      );
```

```
I/flutter (31138): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31138): The following assertion was thrown building FutureBuilder<QuerySnapshot>(dirty, dependencies:
I/flutter (31138): [_InheritedTheme, _LocalizationsScope-[GlobalKey#e254a]], state:
I/flutter (31138): _FutureBuilderState<QuerySnapshot>#d48e4):
I/flutter (31138): 'package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart': Failed assertion:
I/flutter (31138): line 629 pos 16: 'crossAxisCount != null && crossAxisCount > 0': is not true.
I/flutter (31138): 
I/flutter (31138): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31138): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31138): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31138):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (31138): 
I/flutter (31138): When the exception was thrown, this was the stack:
I/flutter (31138): #2      new SliverStaggeredGridDelegateWithFixedCrossAxisCount (package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart:629:16)
I/flutter (31138): #3      new StaggeredGridView.countBuilder (package:flutter_staggered_grid_view/src/widgets/staggered_grid_view.dart:332:28)
I/flutter (31138): #4      _DiscoverScreenState.build.<anonymous closure> (package:companychat/ui/screens/discover.dart:341:48)
I/flutter (31138): #5      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter (31138): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (31138): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (31138): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #9      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (31138): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (31138): #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (31138): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #20     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (31138): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (31138): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #30     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (31138): #31     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (31138): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (31138): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (31138): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #55     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #63     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (31138): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #67     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (31138): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #81     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (31138): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #97     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (31138): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #101    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #107    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (31138): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #113    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (31138): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #117    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (31138): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (31138): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #123    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (31138): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (31138): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (31138): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (31138): #127    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (31138): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (31138): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (31138): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (31138): #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (31138): #132    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
```

right now I have 2 items coming from Firebase (this worked fine with ListView and GridView).
Thank you so much.

**Comment by niuxinhuai** [comment]
'crossAxisCount != null && crossAxisCount > 0': is not true,
This is required

**Comment by FullstackJack** [comment]
Should be closed.
