### ISSUE TITLE
View but scroll and event not working

### ISSUE THREAD

**Issue by faisal-kabir** [letsar/flutter_staggered_grid_view#83]
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'
E/flutter ( 4971): #0      RenderSliverVariableSizeBoxAdaptor.hitTestChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:380:27)
E/flutter ( 4971): #1      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1275:11)
E/flutter ( 4971): #2      SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:847:31)
E/flutter ( 4971): #3      RenderSliverPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:266:14)
E/flutter ( 4971): #4      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1275:11)
E/flutter ( 4971): #5      RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585:24)
E/flutter ( 4971): #6      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795:31)
E/flutter ( 4971): #7      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:723:12)
E/flutter ( 4971): #8      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:581:33)
E/flutter ( 4971): #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #12     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3036:31)
E/flutter ( 4971): #13     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #15     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #16     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161:19)
E/flutter ( 4971): #17     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #19     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #20     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161:19)
E/flutter ( 4971): #21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #23     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #25     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #26     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508:18)
E/flutter ( 4971): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 4971): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #30     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:83:24)
E/flutter ( 4971): #31     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795:31)
E/flutter ( 4971): #32     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752:12)
E/flutter ( 4971): #33     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:21)
E/flutter ( 4971): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #35     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2481:24)
E/flutter ( 4971): #36     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795:31)
E/flutter ( 4971): #37     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752:12)
E/flutter ( 4971): #38     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2476:33)
E/flutter ( 4971): #39     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:366:12)
E/flutter ( 4971): #40     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128:11)
E/flutter ( 4971): #41     RenderProxyBoxMixin.hitTe

**Comment by faisal-kabir** [comment]
use new version
flutter_staggered_grid_view: ^0.3.0
