### ISSUE TITLE
Throws when itemCount is not given

### ISSUE THREAD

**Issue by slosd** [letsar/flutter_staggered_grid_view#95]
With ListView and GridView widgets the `builder` constructors allow to specify no `itemCount` and instead return `null` in the builder function when there is no item left. This does not work with StaggeredGridView, the widget throws an `AssertionError` during `performLayout` which I have included below. There is already a pull request which fixes this issue: https://github.com/letsar/flutter_staggered_grid_view/pull/81

```
I/flutter ( 4954): The following assertion was thrown during performLayout():
I/flutter ( 4954): 'package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart': Failed
I/flutter ( 4954): assertion: line 365 pos 12: 'child != null': is not true.
I/flutter ( 4954): 
I/flutter ( 4954): When the exception was thrown, this was the stack:
I/flutter ( 4954): #2      RenderSliverVariableSizeBoxAdaptor.paintExtentOf (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:365:12)
I/flutter ( 4954): #3      RenderSliverStaggeredGrid.performLayout (package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart:317:54)
I/flutter ( 4954): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
...
```

**Comment by jamesblasco** [comment]
Could you provide some reproducible code for this issue?

**Comment by slosd** [comment]
Here is an example. Also see the pull request I mentioned: https://github.com/letsar/flutter_staggered_grid_view/pull/81
```
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static final _items = List.generate(10, (i) => Text('Tile ${i + 1}'));

  @override
  Widget build(BuildContext context) =>
      MaterialApp(
          title: 'Grid View',
          home: Scaffold(
            body: StaggeredGridView.extentBuilder(
              maxCrossAxisExtent: 150,
              staggeredTileBuilder: (i) => const StaggeredTile.fit(1),
              itemBuilder: (context, i) => i < _items.length ? _items[i] : null,
            ),
          )
      );
}
```

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
